package-lock.json
package.json
src/components/Point/PointScore/PointScoreHeader/index.tsx
src/components/Point/PointScore/index.tsx
src/components/Schedule/ScheduleManage/ScheduleHeader/index.tsx
src/components/Schedule/ScheduleManage/TableView/index.tsx
src/components/Schedule/ScheduleManage/TableView/stlye.ts
src/components/Schedule/ScheduleManage/TableView/style.ts
src/hooks/Point/useGivePointStudent.ts
src/queries/Schedule/schedule.query.ts
src/queries/queryKey.ts
src/repositories/Schedule/schedule.repository.ts
src/repositories/Schedule/schedule.repositoryImpl.ts
src/types/Schedule/types.ts

- 일정 테이블 뷰 무한스크롤 구현
- 상벌점 부여시 사유 리스트 스타일 수정

feat : 일정 테이블 뷰 구현 및 디테일 작업 

---

src/components/Point/Modal/StudentPointInfoModal.tsx
src/components/Point/Modal/constant.ts
src/components/Point/PointReason/PointReasonList/index.tsx
src/components/Point/PointReason/index.tsx
src/components/Point/PointScore/PointScoreHeader/index.tsx
src/components/Point/PointScore/PointScoreTable/index.tsx
src/components/Point/PointScore/constant.ts
src/hooks/Point/useGivePointStudent.ts
src/hooks/Point/useOpenStudentPointModal.tsx
src/hooks/auth/useSignin.ts
src/queries/Point/point.query.ts
src/repositories/Point/point.repository.ts
src/repositories/Point/point.repositoryImpl.ts

- 상벌점 사유 삭제
- 학교 상벌점 api query 수정
- 상벌점 사유 페이지 레이아웃 수정

hotfix : 상벌점 

---

src/components/Point/Modal/StudentPointInfoModal.tsx
src/components/Point/PointScore/PointScoreHeader/index.tsx
src/components/Point/PointScore/PointScoreTable/index.tsx
src/components/Point/PointScore/index.tsx
src/hooks/Point/useGivePointStudent.ts
src/hooks/Point/useOpenStudentPointModal.tsx

- 상벌점 부여 삭제 param값 주어
- 상벌점 부여 학생 전체선택 취소 기능 구현 했습니다.

feat : 상벌점 부여 학생 전체선택 취소 및 상벌점 삭제

---

src/components/Bus/BusModal/BusRegister/index.tsx
src/hooks/Bus/useDeleteBus.ts
src/hooks/Bus/useRegistBus.ts

i added the bus error handling logic.

feat: add bus error handling logic

---

src/components/Point/Modal/GivePointStudentModal.tsx
src/components/Point/Modal/style.ts
src/components/Point/PointReason/PointReasonForm/index.tsx
src/components/Point/PointScore/PointScoreHeader/index.tsx
src/components/Point/PointScore/PointScoreHeader/style.ts
src/components/Point/PointScore/PointScoreTable/index.tsx
src/components/Point/PointScore/index.tsx
src/components/common/Header/index.tsx
src/components/common/Modal/types.ts
src/hooks/Point/useCreatePointReason.ts
src/hooks/Point/useGivePointStudent.ts
src/hooks/Point/useOpenStudentPointModal.tsx
src/hooks/Point/useSetPointStudentIds.ts
src/stores/Point/point.store.ts

date input을 추가하여 confirm으로 입력받는거이 아닌 부여날짜를 선택 할 수 있습니다
- 상벌점 부여 로직 수정
- 상벌점 부여시 사유 선택지 초기화

refactor : 상벌점 부여 로직 수정

---

src/components/Schedule/ScheduleManage/TableView/index.tsx
src/components/Schedule/ScheduleManage/TableView/style.ts
src/components/Schedule/constant.ts
src/hooks/Schedule/useCalendarSchedule.ts
src/hooks/Schedule/useDeleteSchedule.ts
src/utils/Transform/dataTransform.ts

- 스케쥴 테이블 뷰에서 공지 삭제가 안되던 오류 해결
- 테이블 뷰 칼럼 간격 변경
- 테이블 뷰 장소 이름이 ENUM이름 으로 보이던 오류 해결

fix: 학사 일정 관리 테이블 뷰 UI 및 일정 삭제 기능 수정

---

src/components/Point/PointModal/GivePointStudentModal.tsx
src/hooks/Point/useGivePointStudent.ts
src/utils/Transform/textTransform.ts

- "기숙사 지연퇴실(7: 50): 벌점 2점" 이 발급이 안되는 오류 발생
- split을 할때 : 이 두개 이상인 경우 첫번째 : 에서 split이 된다는 것을 발견
- util함수 textTransform을 만들어 세미콜론의 개수에 따라 스플릿 위치 조정

hotfix :: 특정 벌점 수여 불가 이슈 해결 #62

---

src/components/Point/PointModal/GivePointStudentModal.tsx
src/hooks/Point/useGivePointStudent.ts

- 상벌점 부여 시 스크린에 뜨는 Toast의 pointType이 계속 벌점으로 뜨던 오류 수정
수정 전
수정 후

hotfix :: 점수발급Toast pointType 수정 #62

---

src/components/OffBase/OffBaseLeave/index.tsx
src/components/common/Calendars/index.tsx
src/queries/queryKey.ts
src/repositories/OffBaseLeave/offbaseleave.repositoryImpl.ts
src/repositories/OffBaseLeave/offbaseleave.repositroy.ts

- 외박 시스템을 바꾸자라는 결과로 인한 외박 캘린더 삭제

feat :: 외박 캘린더 삭제 #66

---

src/components/OffBase/OffBaseLeave/OffBaseLeaveItem/index.tsx
src/components/OffBase/OffBaseLeave/index.tsx

fix :: 외박 화면 캘린더 완전 삭제 #66

---

package-lock.json
package.json
src/hooks/Schedule/useCalendarSchedule.ts
src/queries/Schedule/schedule.query.ts
src/repositories/Schedule/schedule.repository.ts
src/repositories/Schedule/schedule.repositoryImpl.ts

기간 사이의 일정을 조회하는 api의 파라미터 변경에 따른 api수정

hotfix :: schdule api params 변경 #69

---

src/components/NightStudy/NightStudyAllow/style.ts
src/components/NightStudy/NightStudyToday/NightStudyTodayItem/index.tsx
src/components/NightStudy/NightStudyToday/style.ts
src/hooks/NightStudy/NightStudyAllow/useNightStudyAllow.ts
src/queries/NightStudy/nightstudy.query.ts
src/repositories/NightStudy/nightstudy.repository.ts
src/repositories/NightStudy/nightstudy.repositoryImpl.ts

- 수정사항
심자 신청 리스트 헤더 반응형 처리
심자 승인 취소기능 추가 했습니다

feat :: 심자 취소 기능 추가

---

src/components/Point/PointScore/PointScoreHeader/index.tsx
src/components/Point/PointScore/PointScoreHeader/types.ts
src/components/Point/PointScore/PointScoreTable/index.tsx
src/components/Point/PointScore/index.tsx
src/utils/Transform/csvTransform.ts

기숙사, 학교의 상벌점 목록을 csv데이터화 하는 버튼을 추가하였습니다.
** 학교 상벌점 **
** 기숙사 상벌점 **

상벌점 목록 csv데이터 화

---

src/components/OffBase/OffBasePass/index.tsx

- 이도형 선생님께서 "현재 학교에 남아있는 사람을 파악가능했으면 좋겠다"라는 부탁을 하셨고, 이는 다르게 말하면 "현재 외출자 수가 얼마나 되는지 확인 가능했으면 좋겠다"라고 말할 수 있을것 같아서 현재 외출자 수를 외출페이지에 표시를 하였습니다.
외출 승인된 학생이 존재하지 않을 경우
외출 승인된 학생이 존재할 경우

feat :: 현재 외출자 수 표시 #77

---

src/components/OffBase/OffBaseLeave/index.tsx
src/components/OffBase/OffBasePass/index.tsx
src/components/OffBase/TodayOffBase/index.tsx
src/utils/OffBase/offbaseMemberCalc.ts

외출페이지에만 있던 현재 외출자 수를 외박페이지에서도 외박자를 볼 수 있게 하였습니다.
**외박** 
**현재 외박 중인 학생**

feat :: 외출, 외박자 인원수 표시 #82

---

src/components/OffBase/OffBasePass/OffBasePassItem/index.tsx
src/components/OffBase/OffBasePass/OffBasePassItem/style.ts
src/components/common/SideBar/SideBarDropdown/index.tsx
src/constants/OffBase/offbase.constant.ts
src/types/OffBasePass/offbasepass.type.ts

수요일 자가정비 시간 석식 희망여부를 외출 페이지에다가 추가하였습니다.

feat :: 수요일 자가정비 시간 석식 희망 여부 표시

---

src/components/Schedule/ScheduleManage/TableView/index.tsx
src/hooks/Schedule/useDeleteSchedule.ts
src/queries/Schedule/schedule.query.ts
src/repositories/Schedule/schedule.repository.ts
src/repositories/Schedule/schedule.repositoryImpl.ts

- 테이블 뷰에서 없는 api에 요청을 해서 일정이 뜨지않음
- active된 api로 변경 후 정상 작동 구현
**변경 전**
**변경 후**

fix :: schedule api #85

---

src/components/Out/Redisual/RedisualItem/index.tsx
src/components/Out/Redisual/RedisualItem/style.ts
src/components/Out/Redisual/index.tsx
src/components/Out/Redisual/style.ts
src/components/Router/index.tsx
src/components/common/SideBar/SideBarDropdown/index.tsx
src/constants/Out/offbase.constant.ts
src/hooks/Out/Redisual/useRedisual.ts
src/pages/Out/RedisualPage.tsx
src/queries/Redisual/redisual.query.ts
src/queries/queryKey.ts
src/repositories/Redisual/redisual.repository.ts
src/repositories/Redisual/redisual.repositoryImpl.ts
src/types/Out/out.type.ts
src/utils/Out/redisualMemberCalc.ts

- 현재 날짜 기준 외박 잔류자를 표시하는 페이지를 개발 하였습니다.
- 현재는 프로필필사진, 이름, 반번호, 전화번호가 나오지만 추후 이보다 더 좋은 카테고리가 있다면 반영하겠습니다.

feat :: redisualStudentPage #88

---

src/components/Group/GroupDetail/Modal/groupDetailModal.tsx
src/repositories/Notice/noticeRepositoryImpl.ts

fix :: 경로 error

---

src/components/Auth/Signin/FindPassword/index.tsx
src/components/Auth/Signin/Signin/index.tsx
src/components/Auth/Signin/index.tsx
src/components/Auth/Signup/SignupFirst/index.tsx
src/components/Auth/Signup/SignupFirst/style.ts
src/components/Auth/Signup/SignupSecond/index.tsx
src/components/Auth/Signup/SignupSecond/style.ts
src/components/Auth/Signup/VerifyModal/index.tsx
src/components/Auth/Signup/VerifyModal/style.ts
src/components/Auth/Signup/index.tsx
src/hooks/auth/useSignin.ts
src/hooks/auth/useSignup.ts
src/queries/Member/member.query.ts
src/repositories/Member/MemberRepository.ts
src/repositories/Member/MemberRepositoryImpl.ts
src/types/Member/member.type.ts

!HOTFIX :: teacher signup #127

---

src/components/Club/ClubMain/ClubContext/ClubItemList/index.tsx
src/components/Club/ClubMain/ClubContext/DetailClub/index.tsx
src/components/Club/ClubMain/ClubContext/DetailClub/style.ts
src/components/Club/ClubMain/ClubContext/NoClub/index.tsx

- 멤버 스크롤 
- 동아리 보여주는 상태 변경 (state가 allowed와 pending인 것만 보여주기)

fix :: scroll member #126

---

src/components/NightStudy/NightStudyToday/NightStudyProjectToday/index.tsx

- 번호가 10번인 사람은 24010으로 표시되는 문제가 발생함

Origin/fix/#149 FixProjectNumber

---

src/components/NightStudy/ProjectNightStudyModal/index.tsx
src/components/common/ExtractExcelData/index.tsx
src/queries/NightStudy/nightstudy.query.ts
src/repositories/NightStudy/nightstudy.repository.ts
src/repositories/NightStudy/nightstudy.repositoryImpl.ts
src/types/NightStudy/nightstudy.type.ts

fix : can view member of project #157
